### ISSUE TITLE
æøå characters are shown as ?

### ISSUE THREAD

**Issue by ViperTG** [dfinke/OutTabulatorView#12]
I have just tested with æ,ø & å but the problem might be that UTF-8 is not getting converted to something that JS can use.

![outtabulatorview-encoding](https://user-images.githubusercontent.com/26866146/51800819-86b30100-2235-11e9-8a6b-61943b9094bb.gif)

**Comment by ViperTG** [comment]
Looking at the code it I believe the problem occurs because the html file is written with ascii encoding and not UTF8. Should it not be saved as UFT8 and also the html file should have the HTML document header specifying it to be UTF8.

**Comment by dfinke** [comment]
Thanks! Love the animated gifs. Posting the line of code would be helpful too. Whichever is easiest (or both) are great.

**Comment by dfinke** [comment]
Cool, noticed it runs in 6.2 preview.
