### ISSUE TITLE
[suggestion] Render perfomance improving

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/OutTabulatorView#16]
This code will improve loading render perfomance for long tables but it has a side feature - vertical scrolling moves to datatable. It looks more a hack than a real perfomance solution.
`table` - is a `Tabulator` table variable.
```javascript
// initial data height
height:window.innerHeight - 18, // set height of table to enable virtual DOM

// before </body>
<script type="text/javascript">
    window.addEventListener('resize', function() {
        table.setHeight(window.innerHeight - 18)
    });
</script>
</body>
```

### UPDATE
```javascript
<body>
<div id="datagrid"></div>
...
<script>
var table = new Tabulator("#datagrid", {
    height:"100%", // set height of table to enable virtual DOM
    maxHeight:"100%", // do not let table get bigger than the height of its parent element
    ...
});

window.addEventListener('resize', function() {
    table.setHeight(window.innerHeight - 18)
});

table.on("dataLoading", function(data) {
    if (document.getElementById("datagrid").clientHeight < window.innerHeight) 
    {table.setHeight(window.innerHeight - 18)}
});
</script>
</body>
```

**Comment by dfinke** [comment]
@scriptingstudio Thank you! Are you actively using this?

**Comment by scriptingstudio** [comment]
I do use such configuration because I operate with large tables like 50x1000/2000 cells and render performance makes sense. Tabulator is perfect for comparably small tables but for example 40x700 with full height it is getting desperately slow. And the hack suggested makes life better.
There is yet another framework, Datatables, but it poor documented and requires deep JS experience and more efforts to get results. But it is significantly faster. I am testing both for my projects.

**Comment by scriptingstudio** [comment]
**UPDATE**

For resize callback I actually use this logics:
```javascript
window.addEventListener('resize', function() {
    if (table.setHeight(document.getElementById("datagrid").clientHeight) != (window.innerHeight - 18)) {table.setHeight(window.innerHeight - 18)};
});
```
`-18` is horizontal scroller. I think `clientHeight` property should be used insteadof `innerHeight`. I have to test it.
`resize` is not absolutely reliable because I beleive there is a bug in `redraw` method which is automatically applied when risizing.
