### ISSUE TITLE
Shows blank page in latest Firefox

### ISSUE THREAD

**Issue by majkinetor** [dfinke/OutTabulatorView#4]
```
Loading failed for the <script> with source “c:\Program%20Files\WindowsPowerShell\Modules\OutTabulatorView\1.0.1\js\jquery-3.3.1.min.js”.
tmp7252.html:1
Loading failed for the <script> with source “c:\Program%20Files\WindowsPowerShell\Modules\OutTabulatorView\1.0.1\js\jquery-ui.min.js”.
tmp7252.html:2
Loading failed for the <script> with source “c:\Program%20Files\WindowsPowerShell\Modules\OutTabulatorView\1.0.1\js\tabulator.min.js”.
tmp7252.html:3
Loading failed for the <script> with source “c:\Program%20Files\WindowsPowerShell\Modules\OutTabulatorView\1.0.1\js\jquery.sparkline.min.js”.
tmp7252.html:4
ReferenceError: $ is not defined[Learn More]
tmp7252.html:1116:3
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
tmp7252.html
JQMIGRATE: jQuery is not compatible with Quirks Mode
jquery-migrate-1.0.0.js:29:4
JQMIGRATE: jQuery.browser is deprecated
```

Chrome and Edge work

**Comment by SwarfegaGit** [comment]
Yes, laugh at me now.  IE11 doesn't work either but that's probably never worked.  Shame it's set as the default browser on my works PC.  

I'd love a way to save the generated HTML file rather than just opening it.

**Comment by majkinetor** [comment]
> I'd love a way to save the generated HTML file rather than just opening it.

You can't just ctrl's it or copy it from temp.

**Comment by SwarfegaGit** [comment]
> You can't just ctrl's it or copy it from temp.

How do I automate that?

**Comment by dfinke** [comment]
@SwarfegaGit it saves the html file, use `-Verbose` and it will print that out.

FWIW - It works on my IE11 on my work machine

**Comment by dfinke** [comment]
@majkinetor could you open an issue for that, and I can look at it.

**Comment by SwarfegaGit** [comment]
@dfinke my bad, your correct in both instances.  It looks to be the amount of data being piped in because it fails on my machine with...

    Get-Process | Out-TabulatorView

Using 

    Get-Process -Name powershell | Out-TabulatorView

Works fine.

I would like to see a way to specify an output file or pipe to Out-File.  Being in the verbose comment means I can't automate.

**Comment by dfinke** [comment]
Yup, be great if you could open an issue. Feel free to try your hand at PR

**Comment by dfinke** [comment]
@SwarfegaGit For you local copy, try to update this line:

https://github.com/dfinke/OutTabulatorView/blob/master/OutTabulatorView.psm1#L31

To:

```powershell
$targetData = $records | ConvertTo-Json -Depth 2 -Compress
```

and see if it helps. Let me know

**Comment by majkinetor** [comment]
> @majkinetor could you open an issue for that, and I can look at it.

I already did, that is this issue, LOL :)
